lang: "fr"
app:
  web-client: 1  # 1: activé 0: désactivé
  register: false # activer ou non l'inscription
  register-status: 1 # statut par défaut des utilisateurs inscrits : 1 = activé, 2 = désactivé
  captcha-threshold: 3 # <0: désactivé, 0: toujours, >0: activé après N échecs
  ban-threshold: 0 # 0: désactivé, >0: bannir l'IP après N échecs
  show-swagger: 0 # 1: activé 0: désactivé
  token-expire: 168h
  web-sso: true # authentification web SSO
  disable-pwd-login: false # désactiver la connexion par mot de passe

admin:
  title: "RustDesk API Admin"
  hello-file: "./conf/admin/hello.html"  # utiliser en priorité ce fichier
  hello: ""
  # ID Server and Relay Server ports https://github.com/lejianwen/rustdesk-api/issues/257
  id-server-port: 21116  # port du serveur ID (pour les commandes serveur)
  relay-server-port: 21117 # port du serveur relay (pour les commandes serveur)
gin:
  api-addr: "0.0.0.0:21114"
  mode: "release" # release, debug, test
  resources-path: 'resources'  # dossier de ressources accessibles publiquement
  trust-proxy: ""
gorm:
  type: "sqlite"
  max-idle-conns: 10
  max-open-conns: 100
mysql:
  username: ""
  password: ""
  addr: ""
  dbname: ""
  tls: "false" # true / false / skip-verify / custom

postgresql:
  host: "127.0.0.1"
  port: "5432"
  user: ""
  password: ""
  dbname: "postgres"
  sslmode: "disable" # disable, require, verify-ca, verify-full
  time-zone: "Asia/Shanghai" # fuseau horaire pour PostgreSQL

rustdesk:
  id-server: "192.168.1.66:21116"
  relay-server: "192.168.1.66:21117"
  api-server: "http://127.0.0.1:21114"
  key: ""
  key-file: "/data/id_ed25519.pub"
  personal: 1
  webclient-magic-queryonline: 0
  ws-host: ""  # ex. : wss://192.168.1.3:4443
logger:
  path: "./runtime/log.txt"
  level: "info" # trace, debug, info, warn, error, fatal
  report-caller: true
proxy:
  enable: false
  host: "http://127.0.0.1:1080"
jwt:
  key: ""
  expire-duration: 168h
ldap:
  enable: false
  url: "ldap://ldap.example.com:389"
  tls-ca-file: ""
  tls-verify: false
  base-dn: "dc=example,dc=com"
  bind-dn: "cn=admin,dc=example,dc=com"
  bind-password: "password"

  user:
    base-dn: "ou=users,dc=example,dc=com"
    enable-attr: ""       # Nom de l'attribut permettant d'activer l'utilisateur ; dans AD ça peut être "userAccountControl" ; vide = tous les utilisateurs sont activés.
    enable-attr-value: "" # Valeur de l'attribut lorsque l'utilisateur est activé. Si vous utilisez AD, donnez une valeur arbitraire, elle sera ignorée.
    filter: "(cn=*)"
    username: "uid"       # Nom de l'attribut pour le nom d'utilisateur ; si vous utilisez AD, utilisez "sAMAccountName"
    email: "mail"
    first-name: "givenName"
    last-name: "sn"
    sync: false         # Si true, l'utilisateur est synchronisé dans la base à la connexion. Sinon, la synchronisation se fait lors de la création du compte.
    admin-group: "cn=admin,dc=example,dc=com" # Nom du groupe admin LDAP ; si l'utilisateur appartient à ce groupe, il est admin.
    allow-group: "cn=users,dc=example,dc=com" # Nom du groupe utilisateur LDAP ; si l'utilisateur appartient à ce groupe, il peut se connecter. 
